{{- if not .Values.auth.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edu-version-viewer.fullname" . }}
  labels:
    {{- include "edu-version-viewer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.adminPasswordKey }}: {{ .Values.auth.adminPassword | quote }}
  {{ .Values.auth.viewerPasswordKey }}: {{ .Values.auth.viewerPassword | quote }}
  {{- if .Values.auth.sessionSecret }}
  {{ .Values.auth.sessionSecretKey }}: {{ .Values.auth.sessionSecret | quote }}
  {{- end }}
{{- end }}
